version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/go.zenithar.org/spotigraph
    environment:
      GO111MODULE: "on"
      GOBIN: /go/src/go.zenithar.org/spotigraph/bin
    steps:
      - checkout

      - restore_cache:
          key:
            - mod-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "go.sum" }}-{{ checksum "tools/go.sum" }}
            - mod-cache-v1-{{ arch }}-{{ .Branch }}
            - mod-cache-v1

      - run:
          name: install tools
          command: go run mage.go -d tools go:tools

      - run:
          name: install module
          command: go run mage.go go:deps

      - save_cache:
          key: mod-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "go.sum" }}-{{ checksum "tools/go.sum" }}
          paths:
            - /go/pkg/mod

      - run:
          name: build
          command: go run mage.go build

      - store_test_results:
          path: unit-tests.xml

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - master
